#!/usr/bin/env python3
"""Aura Mail AI - Live Cloud Smoke Test Script (Read-Only by Default).

Performs diagnostic connectivity and inbox checks across configured mailboxes.
Draft creation requires explicit user confirmation.
NEVER sends real email under any circumstances.
"""

import sys
import os
from pathlib import Path

# Add project root to sys.path
PROJECT_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(PROJECT_ROOT))

from backend.config import load_settings, get_user_profile
from backend.provider_manager import provider_manager
from backend.security import mask_secret, get_secret

def run_smoke_tests():
    print("=" * 70)
    print("✨ Aura Mail AI v1.1 - Live Cloud Diagnostics & Smoke Test")
    print("=" * 70)
    
    settings = load_settings()
    profile = get_user_profile()
    demo_mode = settings.get("demo_mode", False)
    
    print(f"\n[1] Environment & Configuration:")
    print(f"    - Safety Mode: {profile.safety_mode} (Default: SAFE_REVIEW)")
    print(f"    - Demo Mode: {demo_mode}")
    print(f"    - Azure Client ID: {mask_secret(settings.get('azure_client_id')) or 'Not configured'}")
    print(f"    - Gemini Key: {'Configured in Keychain' if get_secret('gemini_api_key', 'GEMINI_API_KEY') else 'Offline Heuristics'}")
    print(f"    - Active Default Resume: {profile.active_resume_file}")
    
    print(f"\n[2] Account Health & Connection Validation (Read-Only):")
    accounts = provider_manager.list_all_accounts()
    if not accounts:
        print("    ⚠️  No configured accounts found in settings.json.")
    
    for acc in accounts:
        status_icon = "🟢" if acc.is_connected else "🔴"
        alias_note = f" (Alias of {acc.alias_of})" if acc.is_alias else ""
        print(f"    {status_icon} [{acc.provider.value}] {acc.email_address}{alias_note}")
        print(f"       - Display Name: {acc.display_name}")
        print(f"       - Connected: {acc.is_connected}")
        if acc.last_error:
            print(f"       - Last Error: {acc.last_error}")
        print(f"       - Capabilities: {', '.join(acc.capabilities)}")
    
    print(f"\n[3] Live Inbox Synchronization Check (Read-Only Fetch):")
    try:
        messages, stats = provider_manager.sync_unified_inbox(limit_per_account=5)
        print(f"    - Unified Inbox Count: {len(messages)} messages fetched")
        print(f"    - Mailboxes Synced: {stats.get('accounts_synced', 0)}")
        print(f"    - Mailboxes Failed: {stats.get('accounts_failed', 0)}")
        if stats.get("errors"):
            for err in stats["errors"]:
                print(f"       ⚠️  {err['account_id']}: {err['error']}")
        
        if messages:
            print(f"\n    Sample Message Headers:")
            for i, m in enumerate(messages[:3], 1):
                print(f"       {i}. [{m.folder}] From: {m.sender_name} <{m.sender_email}> | Subject: {m.subject[:50]}")
    except Exception as e:
        print(f"    ❌ Inbox sync exception: {e}")

    print(f"\n[4] Draft Staging Verification (Opt-In Only):")
    print("    By default, smoke tests do not create drafts.")
    print("    To create a test draft in your cloud Drafts folder, run with '--create-test-draft'.")
    
    if "--create-test-draft" in sys.argv:
        print("\n    ⚠️  OPT-IN DRAFT CREATION:")
        confirm = input("    Proceed with creating a test draft in your primary cloud Drafts folder? (yes/no): ")
        if confirm.strip().lower() == "yes":
            if messages:
                target_msg = messages[0]
                print(f"    Creating reply draft for: {target_msg.subject[:40]}...")
                draft_res = provider_manager.save_draft_reply(
                    message_id=target_msg.id,
                    reply_body="[Smoke Test Draft] This is a test draft generated by Aura Mail AI smoke testing.",
                    resume_filename=profile.active_resume_file
                )
                print(f"    Result: {'SUCCESS' if draft_res.success else 'FAILED'}")
                print(f"    Message: {draft_res.safe_message}")
            else:
                print("    No messages available to draft against.")
        else:
            print("    Draft creation skipped.")

    print("\n" + "=" * 70)
    print("✅ Smoke test diagnostics complete. Live email sending was strictly prohibited.")
    print("=" * 70)

if __name__ == "__main__":
    run_smoke_tests()
